### ISSUE TITLE
Setup Firebase/Live Tracking

### ISSUE THREAD

**Issue by tsazo** [tsazo/Consumer#17]
- [x] Setup Firebase
- [x] Access real-time database features
- [x] Publish live locations
- [x] retrieve live locations of driver (in user screen)
